[package]
name = "api-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api-desktop = { path = "../api-desktop" }
api-projects = { path = "../api-projects" }
api-vault = { path = "../api-vault" }
api-workflows = { path = "../api-workflows" }
api-analyzers = { path = "../api-analyzers" }
api-client = { path = "../api-client" }
api-compiler = { path = "../api-compiler" }
api-core = { path = "../api-core" }
api-discovery = { path = "../api-discovery" }
api-mock-runtime = { path = "../api-mock-runtime" }
api-repository = { path = "../api-repository" }
api-storage = { path = "../api-storage" }
api-testing = { path = "../api-testing" }
api-watch = { path = "../api-watch" }
api-workbench = { path = "../api-workbench" }
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
reqwest.workspace = true
